### ISSUE TITLE
내장된 graph algorithm 돌려보기

### ISSUE THREAD

**Issue by caromdreamer** [hsnks100/booang#4]
Algorithms

The BGL algorithms consist of a core set of algorithm patterns (implemented as generic algorithms) and a larger set of graph algorithms. The core algorithm patterns are

Breadth First Search
Depth First Search
Uniform Cost Search
By themselves, the algorithm patterns do not compute any meaningful quantities over graphs; they are merely building blocks for constructing graph algorithms. The graph algorithms in the BGL currently include

Dijkstra's Shortest Paths
Bellman-Ford Shortest Paths
Johnson's All-Pairs Shortest Paths
Kruskal's Minimum Spanning Tree
Prim's Minimum Spanning Tree
Connected Components
Strongly Connected Components
Dynamic Connected Components (using Disjoint Sets)
Topological Sort
Transpose
Reverse Cuthill Mckee Ordering
Smallest Last Vertex Ordering
Sequential Vertex Coloring

**Comment by musicianZem** [comment]
돌려본 코드를 알려 달라는 내용이겠지용?

**Comment by caromdreamer** [comment]
예스

**Comment by musicianZem** [comment]
http://www.boost.org/doc/libs/1_55_0/libs/graph/example/
에서 여러 알고리즘 수행 해보기도 하면서, return type에 대한 고민만 더 해보면 될 것 같습니다.
